---
- name: TSDM Implementation Playbook
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "vcenter01.anpslab.com"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "HPEinvent23!"
    datacenter_name: "datacenter-01"
    # esxi_hosts:
    #   - { name: "esxi_host_1", vmkernel_ip: "10.154.130.10", subnet: "255.255.255.0", gateway: "10.154.130.1" }
    #   - { name: "esxi_host_2", vmkernel_ip: "10.154.130.11", subnet: "255.255.255.0", gateway: "10.154.130.1" }
    vlan_id: "3009"
    port_group_name: "vds_48_tsdm_vlan_1281"
    distributed_switch: "vds02"

  tasks:
    - name: Ensure required VMware libraries are installed
      pip:
        name:
          - pyvmomi
          - requests

    - name: Ensure VMware Ansible collection is installed
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.vmware
        
    - name: Create a vSphere Distributed Switch
      community.vmware.vmware_dvswitch:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter_name: "{{ datacenter_name }}"
        switch_name: "{{ vds_name }}"
        version: 7.0.3
        uplink_quantity: 2
        state: present
      delegate_to: localhost
      

    - name: Create distributed port group
      community.vmware.vmware_dvs_portgroup:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        switch_name: "{{ distributed_switch }}"
        portgroup_name: "{{ port_group_name }}"
        vlan_id: "{{ vlan_id }}"
        number_of_ports: 24
        teaming:
          policy: "loadbalance_srcid"  # Load balancing based on source port ID
          active_uplinks:
            - "uplink1"
            - "uplink2"
          notify_switches: true
          failback: true
        port_binding: static
        state: present

    - name: Configure VMKernel ports on ESXi hosts
      community.vmware.vmware_vmkernel:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ item.name }}"
        portgroup_name: "{{ port_group_name }}"
        network:
          type: 'static'
          ip_address: "{{ item.vmkernel_ip }}"
          subnet_mask: "{{ item.subnet }}"
      loop: "{{ esxi_hosts }}"

    # - name: Add static routes for VMKernel ports
    #   community.vmware.vmware_host_config_manager:
    #     hostname: "{{ vcenter_hostname }}"
    #     username: "{{ vcenter_username }}"
    #     password: "{{ vcenter_password }}"
    #     validate_certs: no
    #     esxi_hostname: "{{ item.name }}"
    #     config_type: "network"
    #     state: present
    #     config_parameters:
    #       - name: "network.ip.route.add"
    #         value: "--gateway {{ item.gateway }} --network {{ item.vmkernel_ip }}/24"
    #   loop: "{{ esxi_hosts }}"

    # - name: Validate VMKernel port connectivity via SSH
    #   ansible.builtin.shell:
    #     cmd: "vmkping -I vmk0 10.154.130.2"
    #   delegate_to: "{{ item.name }}"
    #   become: true
    #   vars:
    #     ansible_ssh_user: "root"  # Replace with the SSH user for ESXi
    #     ansible_ssh_pass: "your-esxi-password"  # Replace with the SSH password for ESXi
    #   loop: "{{ esxi_hosts }}"
